---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/journals":
    get:
      summary: list journals
      responses:
        '200':
          description: successful
    post:
      summary: create journal
      responses:
        '200':
          description: successful
  "/api/v1/journals/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show journal
      responses:
        '200':
          description: successful
    patch:
      summary: update journal
      responses:
        '200':
          description: successful
    put:
      summary: update journal
      responses:
        '200':
          description: successful
    delete:
      summary: delete journal
      responses:
        '200':
          description: successful
  "/api/v1/voices":
    get:
      summary: list voices
      responses:
        '200':
          description: successful
    post:
      summary: create voice
      responses:
        '200':
          description: successful
  "/api/v1/voices/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show voice
      responses:
        '200':
          description: successful
    patch:
      summary: update voice
      responses:
        '200':
          description: successful
    put:
      summary: update voice
      responses:
        '200':
          description: successful
    delete:
      summary: delete voice
      responses:
        '200':
          description: successful
  "/signup":
    post:
      summary: Signup a user
      responses:
        '200':
          description: successful
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    patch:
      summary: update user
      responses:
        '200':
          description: successful
    put:
      summary: update user
      responses:
        '200':
          description: successful
    delete:
      summary: delete user
      responses:
        '200':
          description: successful
  "/signup/sign_up":
    get:
      summary: Retrieves a user
      responses:
        '200':
          description: successful
  "/login":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    post:
      summary: login user
      responses:
        '200':
          description: successful
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: audioscribe.fly.dev/
